#!/bin/bash

# Check if the script is run as root
if [[ $EUID -ne 0 ]]; then
    echo "Error: This script must be run as root." >&2
    exit 1
fi

# Copys Kali Manager to /usr/bin so it will be used like normal commands
cp kali-manager /usr/bin

echo "Kali Manager installed correctly now in the terminal type 'kali-manager' to execute it!"
