#!/bin/bash

# Check if required packages are installed
if ! command -v lolcat &> /dev/null; then
    echo "Some packages are not installed. Installing them now..."
    sudo apt update && sudo apt install -y lolcat
fi

clear

# Display the title
echo "██╗  ██╗ █████╗ ██╗     ██╗    ███╗   ███╗ █████╗ ███╗   ██╗ █████╗  ██████╗ ███████╗██████╗ 
██║ ██╔╝██╔══██╗██║     ██║    ████╗ ████║██╔══██╗████╗  ██║██╔══██╗██╔════╝ ██╔════╝██╔══██╗
█████╔╝ ███████║██║     ██║    ██╔████╔██║███████║██╔██╗ ██║███████║██║  ███╗█████╗  ██████╔╝
██╔═██╗ ██╔══██║██║     ██║    ██║╚██╔╝██║██╔══██║██║╚██╗██║██╔══██║██║   ██║██╔══╝  ██╔══██╗
██║  ██╗██║  ██║███████╗██║    ██║ ╚═╝ ██║██║  ██║██║ ╚████║██║  ██║╚██████╔╝███████╗██║  ██║
╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝    ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝" | lolcat
echo
echo -e "\e[34mTool created by \e[31mUnknowner\e[34m github account \e[31mUnknowner334\e[0m"
echo -e "\e[34mv0.0.3\e[0m"
if [[ $USER == "root" ]]; then
echo -e "\e[33mWelcome \e[31m$USER\e[33m to the Kali Manager\e[0m"
else
echo -e "\e[33mWelcome \e[34m$USER\e[33m to the Kali Manager\e[0m"
fi
echo -e "\e[33mHere you can manage Kali Linux\e[0m"
echo

# Display menu options
while true; do
    echo "Select an option:" | lolcat
    echo -e "                \e[34m[1]. \e[0mUpgrade Kali Linux                       \e[34m[2]. \e[0mUpdate Kali Linux"
    echo -e "                \e[34m[3]. \e[0mInstall a Package/Packages               \e[34m[4]. \e[0mAuto Remove Packages (apt)"
    echo -e "                \e[34m[5]. \e[0mShow disk usage                          \e[34m[6]. \e[0mStart Network Manager"
    echo -e "                \e[34m[7]. \e[0mStop Network Manager                     \e[34m[8]. \e[0mSet a wireless adapter on monitor mode"
    echo -e "                \e[34m[9]. \e[0mSet a wireless adapter on managed mode   \e[34m[10]. \e[0mFull Upgrade Kali Linux"
    echo -e "                \e[34m[0]. \e[0mExit                                     \e[34m[99]. \e[0mCheck for updates"
    echo -e "                \e[34m[*]. \e[0mMaybe Later a lot of functions will be added"
    echo
    read -p "Enter your choice (1-10): " choice

    # Checking if choice are correct and execute a choice
    case $choice in
        1)
            echo "Upgrading Kali Linux..." | lolcat
            sudo apt update && sudo apt upgrade -y
            echo "Upgrade complete!" | lolcat
            ;;
        2)
            echo "Updating Kali Linux..." | lolcat
            sudo apt update
            echo "Update complete!" | lolcat
            ;;
        3)
            echo "Installing a package..." | lolcat
            read -p "Enter a package to install: " package
            sudo apt install -y $package
            echo "Install a Package complete!" | lolcat
            ;;
        4)
            echo "Auto Removing Packages (apt)..." | lolcat
            sudo apt autoremove -y
            echo "Auto Remove Packages (apt) complete!" | lolcat
            ;;
        5)
            echo "Showing disk usage..." | lolcat
            df -h
            ;;
        6)
            echo "Starting NetworkManager..." | lolcat
            sudo service NetworkManager start
            echo "Start NetworkManager complete!" | lolcat
            ;;
        7)
            echo "Stoping NetworkManager..." | lolcat
            sudo service NetworkManager stop
            echo "Stop NetworkManager complete!" | lolcat
            ;;
        8)
            echo "Set a wireless adapter on monitor mode..." | lolcat
            read -p "Choose a wireless adapter: " wlan
            sudo airmon-ng check kill
            sudo airmon-ng start $wlan
            echo "Set a wireless adapter on monitor mode complete!" | lolcat
            ;;
        9)
            echo "Set a wireless adapter on managed mode..." | lolcat
            read -p "Choose a wireless adapter: " wlan
            sudo ifconfig $wlan down && airmon-ng stop $wlan && ifconfig $wlan
            echo "Set a wireless adapter on managed mode complete!" | lolcat
            ;;
        10)
            echo "Full Upgrading Kali Linux..." | lolcat
            sudo apt update && sudo apt -y full-upgrade
            echo "Fully Upgrading Kali Linux complete!" | lolcat
            ;;
        99)
            echo "This feature is not ready..." | lolcat
            ;;
        0)
            echo "Exiting Kali Manager. Goodbye!" | lolcat
            break
            ;;
        *)
            echo "Invalid choice. Please enter a number between 1 and 10." | lolcat
            ;;
    esac

    echo
    read -p "Press Enter to return to the menu..." temp
    clear
    echo "██╗  ██╗ █████╗ ██╗     ██╗    ███╗   ███╗ █████╗ ███╗   ██╗ █████╗  ██████╗ ███████╗██████╗ 
██║ ██╔╝██╔══██╗██║     ██║    ████╗ ████║██╔══██╗████╗  ██║██╔══██╗██╔════╝ ██╔════╝██╔══██╗
█████╔╝ ███████║██║     ██║    ██╔████╔██║███████║██╔██╗ ██║███████║██║  ███╗█████╗  ██████╔╝
██╔═██╗ ██╔══██║██║     ██║    ██║╚██╔╝██║██╔══██║██║╚██╗██║██╔══██║██║   ██║██╔══╝  ██╔══██╗
██║  ██╗██║  ██║███████╗██║    ██║ ╚═╝ ██║██║  ██║██║ ╚████║██║  ██║╚██████╔╝███████╗██║  ██║
╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝    ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝" | lolcat
    echo
    echo -e "\e[34mTool created by \e[31mKaram\e[34m github account \e[31mATRKARAM\e[0m"
    echo -e "\e[34mv0.0.3\e[0m"
    if [[ $USER == "root" ]]; then
    echo -e "\e[33mWelcome \e[31m$USER\e[33m to the Kali Manager\e[0m"
    else
    echo -e "\e[33mWelcome \e[34m$USER\e[33m to the Kali Manager\e[0m"
    fi
    echo -e "\e[33mHere you can manage Kali Linux\e[0m"
    echo
done
